# docker-compose.yml

version: '3.9'  # Необязательный, но лучше указать для совместимости

services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env  # Укажи, если используешь переменные окружения
    # depends_on:
    #   - db

  catalog_service:
    build:
      context: ./catalog_service
    container_name: catalog_service  # Лучше не использовать имя fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./catalog_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./catalog_service/.env
    # depends_on:
    #   - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - catalog_service
      - auth_service

# volumes:
#   postgres_data:
